package lexing;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int ADDOP = 3;
  public static final int INPUT = 25;
  public static final int AND = 9;
  public static final int ELSE = 22;
  public static final int RELOP = 2;
  public static final int INT = 26;
  public static final int OR = 8;
  public static final int RBRACE = 15;
  public static final int RPAREN = 13;
  public static final int WHILE = 29;
  public static final int NOT = 10;
  public static final int SWITCH = 28;
  public static final int IF = 24;
  public static final int COLON = 17;
  public static final int LPAREN = 12;
  public static final int LBRACE = 14;
  public static final int MULOP = 4;
  public static final int ID = 6;
  public static final int CAST = 5;
  public static final int SCOLON = 18;
  public static final int NUM = 7;
  public static final int EQUALS = 11;
  public static final int COMMA = 16;
  public static final int FLOAT = 23;
  public static final int EOF = 0;
  public static final int BREAK = 19;
  public static final int CASE = 20;
  public static final int error = 1;
  public static final int DEFAULT = 21;
  public static final int OUTPUT = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RELOP",
  "ADDOP",
  "MULOP",
  "CAST",
  "ID",
  "NUM",
  "OR",
  "AND",
  "NOT",
  "EQUALS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "COLON",
  "SCOLON",
  "BREAK",
  "CASE",
  "DEFAULT",
  "ELSE",
  "FLOAT",
  "IF",
  "INPUT",
  "INT",
  "OUTPUT",
  "SWITCH",
  "WHILE"
  };
}

